"use client";

import { useEffect, useState } from "react";
import CameraRuntime from "@/components/motion/CameraRuntime";
import CinematicIntro from "@/components/hero/CinematicIntro";
import SoundtrackPanel from "@/components/soundtrack/SoundtrackPanel";
import { awards, certifications, education, experience, leadership, leadershipSkills, projects, skillGroups } from "@/lib/data";

const Arrow = () => <span aria-hidden="true" className="arrow">↗</span>;
const Label = ({ children }: { children: React.ReactNode }) => <p className="label">{children}</p>;

export default function Home() {
  const [quick, setQuick] = useState(false);
  const [menu, setMenu] = useState(false);

  useEffect(() => {
    setQuick(window.localStorage.getItem("rrb-mode") === "quick");
    const observer = new IntersectionObserver((entries) => entries.forEach(({ isIntersecting, target }) => isIntersecting && target.classList.add("is-visible")), { threshold: 0.14 });
    document.querySelectorAll("[data-reveal]").forEach((element) => observer.observe(element));
    return () => observer.disconnect();
  }, []);

  const toggleMode = () => { const next = !quick; setQuick(next); window.localStorage.setItem("rrb-mode", next ? "quick" : "cinematic"); };
  const closeMenu = () => setMenu(false);

  return <div className={quick ? "site quick-view" : "site"}>
    <CameraRuntime />
    <div className="grain" aria-hidden="true" />
    <header className={menu ? "nav-shell is-open" : "nav-shell"}>
      <a className="wordmark" href="#top" aria-label="Ritu Raj Bora home">RITU<span>.</span></a>
      <nav className={menu ? "nav-links open" : "nav-links"} aria-label="Primary navigation"><a href="#work" onClick={closeMenu}>Work</a><a href="#about" onClick={closeMenu}>About</a><a href="#experience" onClick={closeMenu}>Experience</a><a href="#contact" onClick={closeMenu}>Contact</a></nav>
      <div className="nav-actions"><button className="mode-toggle" onClick={toggleMode} aria-pressed={quick}>{quick ? "CINEMATIC" : "QUICK"}</button><button className="menu-toggle" onClick={() => setMenu(!menu)} aria-label="Toggle navigation menu" aria-expanded={menu}><span>{menu ? "CLOSE" : "MENU"}</span><i aria-hidden="true" /></button></div>
    </header>
    <main id="top">
      <CinematicIntro />
      <section className="statement chapter-light" data-atmosphere="quiet" data-reveal><div><Label>CHAPTER 02 / A POINT OF VIEW</Label><h2>Make the digital<br />feel <em>physical.</em></h2></div><p>I work where product thinking, interface craft and visual storytelling overlap — shaping experiences that are useful enough to return to and distinctive enough to remember.</p><span className="side-caption">SYSTEM / 001 — KEEP IT HUMAN</span></section>
       <section id="work" className="work chapter" data-atmosphere="work"><div className="chapter-heading" data-reveal><div><Label>CHAPTER 03 / SELECTED WORK</Label><h2>Worlds,<br /><em>not cards.</em></h2></div><p>Selected work across civic technology, product, frontend and design systems.</p></div><div className="project-stack">{projects.map((project, index) => <Project key={project.title} index={String(index + 1).padStart(2, "0")} title={project.title} period="SELECTED PROJECT" type="PROJECT" variant={project.variant} description={project.description} tags={project.stack} image={project.image} reverse={index % 2 === 1} />)}</div><p className="archive-note">CASE STUDY ARCHIVE / ORIGINAL SCREENS, PROTOTYPES AND REELS IN DEVELOPMENT</p></section>
          <section className="motion-reel chapter" data-atmosphere="reel" data-reveal aria-labelledby="reel-title"><div className="reel-copy"><Label>CHAPTER 04 / THE SOUNDTRACK</Label><h2 id="reel-title">Design sounds better<br /><em>with music.</em></h2><p>Every design session has a soundtrack. These are the songs I keep playing while designing, editing, prototyping, and getting lost in the details.</p><span className="reel-status">DESIGN / FOCUS / REPEAT</span></div><SoundtrackPanel /></section>
       <section id="experience" className="experience chapter-light" data-atmosphere="time"><div className="chapter-heading" data-reveal><div><Label>CHAPTER 05 / EXPERIENCE</Label><h2>A line through<br /><em>time.</em></h2></div><span className="year-mark">2023 — NOW</span></div><div className="timeline">{experience.map((item) => <article className="timeline-item" data-camera data-reveal key={item.company}><span className="timeline-year">{item.year}</span><div><Label>{item.type} / {item.period}</Label><h3>{item.company}</h3><p><strong>{item.role}</strong><br />{item.description}</p></div></article>)}</div></section>
       <section id="education" className="education-section chapter-light" data-atmosphere="education" data-reveal><div className="chapter-heading"><div><Label>CHAPTER 06 / EDUCATION</Label><h2>Learning<br /><em>in progress.</em></h2></div><span className="year-mark">2021 — 2027</span></div><div className="timeline">{education.map((item) => <article className="timeline-item education-item" data-camera data-reveal key={item.institution}><span className="timeline-year">{item.period.slice(0, 4)}</span><div><Label>EDUCATION / {item.period}</Label><h3>{item.institution}</h3><p><strong>{item.degree}</strong><br />{item.field}</p></div></article>)}</div></section>
       <section id="about" className="about chapter" data-atmosphere="still" data-reveal><div className="about-rail"><Label>CHAPTER 06 / ABOUT</Label><span>DESIGN<br />BUILD<br />EDIT</span></div><div className="about-copy"><h2>Design.<br />Build.<br /><em>Edit.</em></h2><p>I&apos;m Ritu Raj Bora, a product designer with a frontend engineering foundation and a background in graphic design and motion. I care about the small decisions that make interfaces clearer, more expressive and easier to remember.</p><div className="discipline-list">{leadershipSkills.map((item, index) => <div key={item}><span>0{index + 1}</span><strong>{item}</strong></div>)}</div></div></section>
       <section className="gallery chapter" data-atmosphere="gallery" data-reveal aria-labelledby="gallery-title"><div className="gallery-heading"><Label>CHAPTER 07 / MY ELEMENTS</Label><h2 id="gallery-title">An exhibition<br />in <em>motion.</em></h2></div><div className="poster-wall" aria-label="Abstract graphic-design exhibition"><a className="poster poster-a" href="https://pin.it/6g8X6fLkF" target="_blank" rel="noreferrer"><img className="poster-image" src="/images/form1.PNG" alt="Memories in Grain visual archive poster" loading="lazy" decoding="async" /></a><a className="poster poster-b" href="https://www.behance.net/riiiituraaj" target="_blank" rel="noreferrer" aria-label="Open Ritu Raj Bora Behance profile"><img className="poster-image" src="/images/branddesign.png" alt="Brand design visual" loading="lazy" decoding="async" /></a><VideoDisplayTile /></div></section>
      <section className="awards chapter-light" data-atmosphere="awards"><div className="chapter-heading" data-reveal><div><Label>CHAPTER 08 / RECOGNITION</Label><h2>Good work<br /><em>travels.</em></h2></div></div><div className="award-list">{awards.map((award) => <article className="award" data-reveal key={award.name}><span>{award.number}</span><div><Label>{award.name}{award.detail ? ` / ${award.detail}` : ""}</Label><h3>{award.place}</h3></div><Arrow /></article>)}</div></section>
       <section className="toolkit chapter" data-atmosphere="tools" data-reveal><div><Label>SCENE 09 / TOOLKIT</Label><h2>Many tools.<br /><em>One eye.</em></h2></div><div className="skill-groups">{skillGroups.map((group) => <div className="skill-group" key={group.number}><Label>{group.number} / {group.title}</Label><div className="skill-cloud">{group.skills.map((skill) => <span key={skill}><BrandIcon name={skill} />{skill}</span>)}</div></div>)}</div></section>
       <section className="profile-details chapter-light" data-atmosphere="details" data-reveal><div className="chapter-heading"><div><Label>SCENE 10 / CREDENTIALS</Label><h2>Built through<br /><em>practice.</em></h2></div></div><div className="detail-list">{certifications.map((item) => <article className="detail-item" key={item.title}><Label>{item.issuer}</Label><h3>{item.title}</h3><p>{item.description}</p></article>)}</div><div className="leadership"><Label>LEADERSHIP</Label>{leadership.map((item) => <p key={item}>{item}</p>)}</div></section>
       <section id="contact" className="contact chapter" data-atmosphere="end" data-reveal><Label>SCENE 08 / END CREDITS</Label><h2>The end.<br /><em>Not yet.</em></h2><p>Let&apos;s make something feel alive.</p><div className="contact-links"><a href="mailto:riturajbora291@gmail.com">Email / riturajbora291@gmail.com <Arrow /></a><a href="https://www.linkedin.com/in/ritu-raj-bora/" target="_blank" rel="noreferrer">LinkedIn / ritu-raj-bora <Arrow /></a><a href="https://github.com/riiiituraaj" target="_blank" rel="noreferrer">GitHub / riiiituraaj <Arrow /></a><a href="https://www.figma.com/files/team/1429475554754734128/user/1358119824858413595?fuid=1358119824858413595" target="_blank" rel="noreferrer">Figma / Ritu Raj Bora <Arrow /></a><a href="https://www.behance.net/riiiituraaj" target="_blank" rel="noreferrer">Behance / @riiiituraaj <Arrow /></a><a href="https://www.instagram.com/riiiituraaj/" target="_blank" rel="noreferrer">Instagram / @riiiituraaj <Arrow /></a><a href="tel:+919394713455">+91-93947-13455 <Arrow /></a></div><footer><span>RITU RAJ BORA / DESIGNED, BUILT, EDITED</span><span>© 2026 / FADE TO MIDNIGHT</span></footer></section>
    </main>
  </div>;
}

function Project({ index, title, period, type, variant, description, tags, image, reverse = false }: { index: string; title: string; period: string; type: string; variant: "interface" | "code" | "film"; description: string; tags: string[]; image?: string; reverse?: boolean }) {
  return <article className={`project ${reverse ? "reverse" : ""}`} data-camera><div className={`project-visual visual-${variant}`} role="img" aria-label={`${title} visual study`}>{image && <img className="project-thumbnail" src={image} alt={`${title} project preview`} loading="lazy" decoding="async" />}<span className="visual-meta">{type} / {index}</span>{!image && variant === "interface" && <div className="interface-study"><header><i /><i /><i /></header><div><b>{title.slice(0, 8).toUpperCase()}</b><span /><span /><span /></div></div>}{!image && variant === "code" && <pre><code><span>const</span> clarity = &#123;{`\n`}  shape: <b>"intent"</b>,{`\n`}  motion: <b>"quiet"</b>,{`\n`}  result: <b>true</b>{`\n`}&#125;;</code></pre>}{!image && variant === "film" && <div className="film-study"><i /><b /><span /></div>}<span className="visual-time">FRAME / 00:01:{index}4</span></div><div className="project-copy"><span className="project-number">{index}</span><div><Label>{period}</Label><h3>{title}</h3><p>{description}</p><div className="tags">{tags.map((tag) => <span key={tag}><BrandIcon name={tag} />{tag}</span>)}</div></div><Arrow /></div></article>;
}

const icons: Record<string, string> = { "React.js": "react", "Next.js": "nextdotjs", "Node.js": "nodedotjs", "Express.js": "express", JavaScript: "javascript", TypeScript: "typescript", "REST APIs": "swagger", "Responsive Web Development": "css3", MongoDB: "mongodb", PostgreSQL: "postgresql", MySQL: "mysql", Firebase: "firebase", "UI/UX Design": "figma", Wireframing: "figma", Prototyping: "figma", "Design Systems": "figma", "Interaction Design": "figma", "Visual Design": "adobeillustrator", "Git & GitHub": "github", Docker: "docker", Vercel: "vercel", Figma: "figma", "Adobe Photoshop": "adobephotoshop", "Adobe After Effects": "adobeaftereffects", "Graphic Design": "adobeillustrator", "Motion Graphics": "adobeaftereffects", Branding: "adobeillustrator", "Creative Direction": "adobecreativecloud", Python: "python" };
function BrandIcon({ name }: { name: string }) { const slug = icons[name]; return slug ? <img className="brand-icon" src={`https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/${slug}.svg`} alt="" onError={(event) => { event.currentTarget.hidden = true; }} /> : null; }

function VideoDisplayTile() {
  return <a className="poster poster-c video-display-tile" href="https://www.instagram.com/ritual.frames/" target="_blank" rel="noreferrer" role="group" aria-label="Open A Life in Frames on Instagram" onMouseEnter={(event) => { if (window.matchMedia("(hover: none)").matches) return; const video = event.currentTarget.querySelector("video"); if (video) void video.play().catch(() => undefined); }} onMouseLeave={(event) => { const video = event.currentTarget.querySelector("video"); if (video) { video.pause(); video.currentTime = 0; } }}><video className="video-tile-video" muted playsInline preload="none" poster="/images/midnight-dreamscape.png" aria-label="A Life in Frames"><source src="/videos/motion.mp4" type="video/mp4" /><source src="/videos/motion.MOV" type="video/quicktime" /></video><div className="video-tile-overlay" /><span className="video-tile-time">00:00:24</span><strong className="video-tile-title">A Life<br />in Frames</strong><span className="video-tile-play" aria-hidden="true" /><div className="video-tile-progress" aria-hidden="true"><i /></div></a>;
}
